import type { User, InventoryItem, BorrowRequest, Department, SubDepartment } from "./types"

export const mockDepartments: Department[] = [
  {
    id: "dept-1",
    name: "IT Department",
    description: "Information Technology",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "dept-2",
    name: "Operations",
    description: "Operations and Logistics",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "dept-3",
    name: "Finance",
    description: "Finance and Accounting",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "dept-4",
    name: "Marketing",
    description: "Marketing and Communications",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
]

export const mockSubDepartments: SubDepartment[] = [
  {
    id: "subdept-1",
    name: "Infrastructure",
    departmentId: "dept-1",
    description: "IT Infrastructure and Support",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "subdept-2",
    name: "Development",
    departmentId: "dept-1",
    description: "Software Development",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "subdept-3",
    name: "Logistics",
    departmentId: "dept-2",
    description: "Logistics and Supply Chain",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "subdept-4",
    name: "Accounting",
    departmentId: "dept-3",
    description: "Accounting and Reporting",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "subdept-5",
    name: "Digital Marketing",
    departmentId: "dept-4",
    description: "Digital Marketing and Social Media",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
]

export const mockUsers: User[] = [
  {
    id: "1",
    email: "adminarsa@clientname.com",
    name: "Administrator",
    role: "admin",
    department: "IT",
    departmentId: "dept-1",
    subDepartmentId: "subdept-1",
    passwordHash: "5f4dcc3b5aa765d61d8327deb882cf99", // password: "password"
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "2",
    email: "staff1@clientname.com",
    name: "Staff Member 1",
    role: "staff",
    department: "Operations",
    departmentId: "dept-2",
    subDepartmentId: "subdept-3",
    passwordHash: "5f4dcc3b5aa765d61d8327deb882cf99", // password: "password"
    createdAt: new Date("2024-01-15"),
  },
  {
    id: "3",
    email: "staff2@clientname.com",
    name: "Staff Member 2",
    role: "staff",
    department: "Finance",
    departmentId: "dept-3",
    subDepartmentId: "subdept-4",
    passwordHash: "5f4dcc3b5aa765d61d8327deb882cf99", // password: "password"
    createdAt: new Date("2024-02-01"),
  },
]

export const mockInventoryItems: InventoryItem[] = [
  {
    id: "1",
    name: 'MacBook Pro 16"',
    description: "Apple MacBook Pro 16-inch with M2 Pro chip",
    category: "Laptops",
    serialNumber: "MBP-001",
    condition: "excellent",
    status: "available",
    location: "IT Storage Room A",
    purchaseDate: new Date("2024-01-15"),
    purchasePrice: 2499,
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15"),
  },
  {
    id: "2",
    name: 'Dell Monitor 27"',
    description: "Dell UltraSharp 27-inch 4K Monitor",
    category: "Monitors",
    serialNumber: "MON-002",
    condition: "good",
    status: "borrowed",
    location: "IT Storage Room A",
    purchaseDate: new Date("2024-02-01"),
    purchasePrice: 599,
    createdAt: new Date("2024-02-01"),
    updatedAt: new Date("2024-03-15"),
  },
  {
    id: "3",
    name: "Wireless Presenter",
    description: "Logitech Spotlight Wireless Presenter",
    category: "Accessories",
    serialNumber: "PRES-003",
    condition: "excellent",
    status: "available",
    location: "Conference Room B",
    purchaseDate: new Date("2024-01-20"),
    purchasePrice: 129,
    createdAt: new Date("2024-01-20"),
    updatedAt: new Date("2024-01-20"),
  },
]

export const mockBorrowRequests: BorrowRequest[] = [
  {
    id: "1",
    itemId: "2",
    borrowerId: "2",
    requestedDate: new Date("2024-03-10"),
    expectedReturnDate: new Date("2024-03-24"),
    status: "active",
    purpose: "Client presentation setup",
    approvedBy: "1",
    approvedAt: new Date("2024-03-11"),
    notes: "Approved for marketing presentation",
    createdAt: new Date("2024-03-10"),
    updatedAt: new Date("2024-03-11"),
  },
  {
    id: "2",
    itemId: "1",
    borrowerId: "3",
    requestedDate: new Date("2024-03-20"),
    expectedReturnDate: new Date("2024-04-03"),
    status: "pending",
    purpose: "Remote work setup",
    notes: "Need for upcoming business trip",
    createdAt: new Date("2024-03-20"),
    updatedAt: new Date("2024-03-20"),
  },
]
